### PR TITLE
Update insecure packages

### PR DESCRIPTION
**Pull request by hkz-aarvesen**
# What Are We Doing Here

Update insecure python packages.  Additionally, address linting failures.

### CODE REVIEW

**Comment by nicolerenee** [comment]
Code looks fine. Assuming everything passes this is good to get merged, however you will need to squash everything down to a single commit and then also make sure you sign off on the commit when you make it.

**Comment by hkz-aarvesen** [comment]
I'm happy to squash it all.  What does sign off on the commit mean?

Need a code owner to click the approve button before I can do the merge 😃

**Comment by nicolerenee** [comment]
You will need to squash before the merge since this repo won't allow you to squash merge as then we lose the DCO signoff.

For signing off check out: https://github.com/wpengine/lostromos/blob/master/CONTRIBUTING.md#sign-your-work

**Comment by hkz-aarvesen** [comment]
Squashed, signed, and force pushed.  Waiting on the rebuild.

**Comment by hkz-aarvesen** [comment]
Thanks for the merge, Nicole!

**Pull request merged**
